version: '0.1'
paths:
  specs: .specwright/specs
  aips: .specwright/aips
repo:
  default_branch: main
user:
  default_owner: null
current:
  spec: .specwright/specs/email-gmail-addition.md
  aip: /workspace/life/.specwright/aips/email-gmail-addition.yaml
