version: '0.1'
paths:
  specs: .specwright/specs
  aips: .specwright/aips
repo:
  default_branch: main
user:
  default_owner: null
current:
  spec: .specwright/specs/life-jobs-verbs-refactor.md
  aip: /workspace/life-cli/.specwright/aips/llm-processing-ho.yaml
