# Dataverse job definitions

jobs:
  dataverse.query_contacts:
    description: "Query active contacts from Dataverse"
    steps:
      - name: query
        call: life_jobs.dataverse.query
        args:
          account: lifeos
          entity: contacts
          select: [firstname, lastname, emailaddress1, modifiedon]
          filter: "statecode eq 0"
          orderby: "modifiedon desc"
          top: 100
          output: ~/data/contacts.json

  dataverse.query_accounts:
    description: "Query accounts from Dataverse"
    steps:
      - name: query
        call: life_jobs.dataverse.query
        args:
          account: lifeos
          entity: accounts
          select: [name, accountid, createdon]
          filter: "statecode eq 0"
          output: ~/data/accounts.json

  dataverse.get_contact:
    description: "Fetch a single contact by ID"
    steps:
      - name: fetch
        call: life_jobs.dataverse.get_single
        args:
          account: lifeos
          entity: contacts
          record_id: "{contact_id}"
          select: [firstname, lastname, emailaddress1, telephone1]
