# LLM generate job definitions

jobs:
  generate.prompt:
    description: "Simple LLM prompt"
    steps:
      - name: generate
        call: life_jobs.generate.prompt
        args:
          prompt: "{user_prompt}"
          model: gpt-4o-mini
          output: ~/output/response.md

  generate.summarize:
    description: "Summarize JSON data with context"
    steps:
      - name: generate
        call: life_jobs.generate.prompt_with_context
        args:
          prompt: "Summarize the key points from this data."
          context_files: ["{input_file}"]
          system: "You are a helpful assistant that provides concise summaries."
          output: ~/output/summary.md

  generate.batch:
    description: "Process a batch of items through LLM"
    steps:
      - name: batch
        call: life_jobs.generate.batch
        args:
          items_file: "{items_file}"
          prompt: "Analyze the following item and provide insights."
          output: ~/output/batch_results.json
          model: gpt-4o-mini
          max_retries: 3
          rate_limit_rpm: 60

  generate.healthcheck:
    description: "Verify llm library is available and configured"
    steps:
      - name: ping
        call: life_jobs.generate.prompt
        args:
          prompt: "Respond with exactly: OK"
          model: gpt-4o-mini
