# Multi-step workflow job definitions

jobs:
  workflow.daily_data_pull:
    description: "Pull daily data from multiple sources"
    steps:
      - name: contacts
        call: life_jobs.dataverse.query
        args:
          account: lifeos
          entity: contacts
          filter: "statecode eq 0"
          output: ~/data/contacts.json

      - name: emails
        call: life_jobs.graph.get_messages
        args:
          account: personal
          top: 50
          output: ~/data/emails.json

      - name: calendar
        call: life_jobs.graph.get_calendar_events
        args:
          account: personal
          top: 10
          output: ~/data/calendar.json
