# Writeback job definitions
# Copy to ~/.life/jobs/writeback.yaml
#
# Writeback enables bidirectional sync between projected markdown files and Dataverse.
# Files must have frontmatter with: entity, record_id, projected_at, editable_fields
#
# Workflow:
#   1. Run writeback_plan to scan for changes and generate a plan
#   2. Review the plan at ~/.life/writeback/plan.json
#   3. Run writeback_apply to push changes to Dataverse

jobs:
  writeback_plan:
    description: "Scan vault and build writeback plan for changed files"
    steps:
      - name: plan
        call: life_jobs.writeback.plan_writeback
        args:
          vault_root: ~/clinical-vault/views
          plan_path: ~/.life/writeback/plan.json
          glob_pattern: "**/*.md"

  writeback_apply:
    description: "Apply writeback plan to Dataverse"
    steps:
      - name: apply
        call: life_jobs.writeback.apply_writeback
        args:
          account: clinic
          plan_path: ~/.life/writeback/plan.json

  # Combined workflow: plan then apply (use with caution)
  writeback_sync:
    description: "Plan and apply writeback in one step"
    steps:
      - name: plan
        call: life_jobs.writeback.plan_writeback
        args:
          vault_root: ~/clinical-vault/views
          plan_path: ~/.life/writeback/plan.json
          glob_pattern: "**/*.md"
      - name: apply
        call: life_jobs.writeback.apply_writeback
        args:
          account: clinic
          plan_path: ~/.life/writeback/plan.json
