"""
Initialize a new Life-CLI project.

Creates project-local configuration in .life/config.yml

Copyright 2025 Ben Mensi
Licensed under the Apache License, Version 2.0
"""

import logging
from pathlib import Path
from typing import Optional

import typer
import yaml

app = typer.Typer(help="Initialize a new Life-CLI project")

logger = logging.getLogger(__name__)


@app.callback(invoke_without_command=True)
def init(
    ctx: typer.Context,
    force: bool = typer.Option(
        False,
        "--force",
        "-f",
        help="Overwrite existing config if present"
    ),
    workspace: Optional[str] = typer.Option(
        None,
        "--workspace",
        "-w",
        help="Workspace directory (defaults to current directory)"
    ),
):
    """
    Initialize a new Life-CLI project.

    Creates .life/config.yml with sensible defaults for the current project.
    The config file is placed in .life/ (similar to .git/) to keep your
    project root clean.

    Example:
        life init                    # Use current directory as workspace
        life init --workspace ~/data # Set specific workspace path
        life init --force            # Overwrite existing config
    """
    dry_run = ctx.obj.get("dry_run", False) if ctx.obj else False
    verbose = ctx.obj.get("verbose", False) if ctx.obj else False

    # Paths
    project_dir = Path.cwd()
    config_dir = project_dir / ".life"
    config_file = config_dir / "config.yml"

    # Check if already initialized
    if config_file.exists() and not force:
        typer.secho(
            f"⚠️  Project already initialized: {config_file}",
            fg=typer.colors.YELLOW
        )
        typer.echo("Use --force to overwrite existing config")
        raise typer.Exit(1)

    # Determine workspace
    if workspace:
        workspace_path = str(Path(workspace).expanduser().resolve())
    else:
        workspace_path = str(project_dir.resolve())

    # Create default config
    default_config = {
        "workspace": workspace_path,
        "today": {
            "daily_dir": f"{workspace_path}/notes/daily",
            "template_path": f"{workspace_path}/notes/templates/daily-ops.md"
        },
        "sync": {},
        "merge": {},
        "process": {},
        "status": {}
    }

    if verbose:
        logger.debug(f"Project directory: {project_dir}")
        logger.debug(f"Config directory: {config_dir}")
        logger.debug(f"Config file: {config_file}")
        logger.debug(f"Workspace: {workspace_path}")

    if dry_run:
        typer.echo("[DRY RUN] Would create:")
        typer.echo(f"  Directory: {config_dir}")
        typer.echo(f"  Config:    {config_file}")
        typer.echo("\n[DRY RUN] Config content:")
        typer.echo("─" * 60)
        typer.echo(yaml.dump(default_config, default_flow_style=False, sort_keys=False))
        typer.echo("─" * 60)
        return

    # Create directory
    config_dir.mkdir(parents=True, exist_ok=True)

    # Write config file
    with open(config_file, 'w') as f:
        # Add header comment
        f.write("# Life-CLI Project Configuration\n")
        f.write("# Generated by: life init\n")
        f.write(f"# Project: {project_dir.name}\n\n")
        yaml.dump(default_config, f, default_flow_style=False, sort_keys=False)

    typer.secho(f"✅ Initialized Life-CLI project in {config_dir}", fg=typer.colors.GREEN)
    typer.echo(f"\nConfig file: {config_file}")
    typer.echo(f"Workspace:   {workspace_path}")
    typer.echo("\nNext steps:")
    typer.echo("  1. Edit .life/config.yml to add your tasks")
    typer.echo("  2. Run 'life sync <task>' to execute tasks")
    typer.echo("  3. Run 'life today' to create daily notes")
    typer.echo("\nSee: life --help for all commands")


if __name__ == "__main__":
    app()
